baudrate: '115200'
elevation: '0'
file: ''
labels:
- id: time
  num: 13
  text: 'Time:'
- id: send_num
  num: 2
  text: 'Packet Sent num:'
- id: rssi
  num: 1
  text: 'RSSI:'
- id: positionX
  num: 3
  text: 'Pozycja X:'
- id: positionY
  num: 4
  text: 'Pozycja Y:'
- id: altitude
  num: 5
  text: "Wysoko\u015B\u0107:"
- id: pressure
  num: 6
  text: "Ci\u015Bnienie:"
- id: temperature
  num: 7
  text: 'Temperatura:'
- id: pm25
  num: 9
  text: 'PM-2,5:'
- id: pm10
  num: 10
  text: 'PM-10:'
- id: humidity
  num: 11
  text: 'Humidity:'
- id: air_quality
  num: 8
  text: 'Air Quality:'
- id: battery
  num: 12
  text: 'Battery:'
multi_prediction: false
port: COM11
port_num: 3
positionX: '1'
positionY: '1'
prediction: true
pressure: '1013.25'
save_path: C:/
start_positionX: '50.477696'
start_positionY: '19.472804'
timeout: '1'
version: '1.2'
