baudrate: '115200'
elevation: '1'
file: ''
labels:
- id: elevation
  num: 0
  text: 'Start elevation:'
  value: '1'
- id: time
  num: 9
  text: 'Time:'
- id: rssi
  num: 1
  text: 'RSSI:'
- id: positionX
  num: 2
  text: 'Pozycja X:'
- id: positionY
  num: 3
  text: 'Pozycja Y:'
- id: altitude
  num: 4
  text: "Wysoko\u015B\u0107:"
- id: pressure
  num: 5
  text: "Ci\u015Bnienie:"
- id: temperature
  num: 6
  text: 'Temperatura:'
- id: pm25
  num: 7
  text: 'PM-2,5:'
- id: pm10
  num: 8
  text: 'PM-10:'
port: COM11
port_num: 3
positionX: '1'
positionY: '1'
prediction: true
timeout: '1'
version: '1.1'
